### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [Joannie/TwitterMockApp#1]

**Comment by nesquena** [comment]
The original comment was posted in error. This project is currently missing the following required story:

- [ ] User can view more tweets as they scroll with infinite pagination. Number of tweets is unlimited. However there are Twitter Api Rate Limits in place.

Please re-submit this project to us with pagination completed within 24 hours.

**Comment by Joannie** [comment]
Hi @nesquena , thanks for reminder, I just provided and updated the missing part - pagination.

**Comment by codepathreview** [comment]
Hello Joannie,

:+1: Congrats on completing the third project! Nice work overall. We hope you'll be able to complete more optionals and/or improve the look and feel of the app in the future. In a few hours, a "Report" tab will show up in the course system that will give you more details about your submission.

I have provided a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission.

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, Models, Authentication, API Communication, Preferences, ActionBar, et al) and see how they all fit together.

**Comment by Joannie** [comment]
Hi Codepath, 

Thanks for the feedback. I'd love to share with you that in this project, I really learned a lot from implementation.  Although I didn't finish all the stretches, I still feel it sharpens the Android skill a lot. Just need more time to digest.  Btw, the on-site coaches are really supportive. We even stayed longer after the Monday's session in order to refresh some logic. 

//Joannie

**Comment by nesquena** [comment]
That's great to hear! Glad this assignment has helped the different pieces come together for you. And we are happy that the coaches have been able to help out. Thanks for the note!

**Comment by codepathreview** [comment]
Hello Joannie,

:+1: Project looks fine. Great to see you completed many optional features and spent time improving the look and feel of the app. In a few hours, a "Report" tab will show up in the course system that will give you more details about your submission.

I have provided a detailed [Project 4 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_4_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you might be able to improve your submission.

Let us know if you have any other thoughts or questions about this assignment. Hopefully you can see this coming together as a "fully fledged" twitter client with some more work and polish. This app contains all of the components now (fragments, models, networking, client, tab navigation, image loading, et al) of 90% of dynamic data-driven API client. Obviously there are lots of details and patterns to learn, but by this point you have been introduced to all the major frameworks and concepts. Hopefully you would feel fairly confident getting started making Android apps for instagram, pinterest, yardsale, flickr, <insert api client here> using the same patterns.
